### PR TITLE
Misc frontend fixes

### PR DESCRIPTION
**Pull request by vincerubinetti**
- switch all util hooks from `react-use` to `@reactuses/core`. former has too many bugs and holes in functionality. also considered `mantine/hooks`, but immediately ran into [several issues](https://github.com/orgs/mantinedev/discussions?discussions_q=author%3Avincerubinetti+). looked into several other libraries ([1](https://github.com/juliencrn/usehooks-ts) [2](https://github.com/uidotdev/usehooks) [3](https://github.com/alibaba/hooks)), but they were all missing features we needed.
- fix cache key bug leading to incorrect responses
- add "analysis card" component for showing most recently submitted analyses
- move font awesome v5 icons to v6
- use link component for all links everywhere in app
- refactor link component prop types, make sure state is always preserved
- remove custom mutation observer hook and use aforementioned util lib
- add "recent analyses" section to load analysis page. save a few of most recently submitted analyses (inputs only), and add warning about not relying on this too heavily.
- hide 3 fold cross validation when all `-10`s. round to 2 decimal places.
- fix bug in isCovering util func

### CODE REVIEW

**Comment by ChristopherMancuso** [comment]
@vincerubinetti the way the results are now, if the python package was to run the model twice so the google function returned two sets of results at the same time, one for a model species and one for human, would the browser be able to handle that much data coming back from the google function? 

Like are the results that are returned from the google function always stored in cache, or is that something specific if the google function needs to be run twice. I have a very rudimentary understanding of cache.

**Comment by vincerubinetti** [comment]
@ChristopherMancuso The current results are around 5 MB. That is for the example genesets which are about 10 genes. I'm not sure how the size of the response would scale up with the number of input genes? Linearly?

Even 100 MB can be handled by a server or browser, but at a certain point, you want to be mindful of user's internet bandwidth. As a user, I don't want a website making a 100 MB request, even if I'm on desktop... unless I'm downloading a big application or something.

There's no hard-coded limits (in the spec) for how big HTTP requests can be, but specific servers/browsers/devices might have hard limits that vary and are hard to look up and verify. As such, let's consider 100 MB a practical limit that should work fine on any modern tech.

Caching is more complicated as it can happen at multiple points in the whole pipeline. For example, my frontend caches responses "in memory" so it doesn't make the same request twice in the same "tab session" (if you refresh the tab, or open the app in a new tab, the cache is reset). Browsers also cache things based on the type of resource and HTTP headers present in the request/response. Servers can also implement a variety of caching mechanisms, but since we haven't set up one explicitly for our cloud functions, I think/hope Google hasn't done any hidden caching magic for us.

I hope this helps, though I think it's best to just forget about cache when considering transfer limits and such. That is, just pretend caching doesn't exist, because that will be the worst case scenario and that's what you should design for.

**Comment by ChristopherMancuso** [comment]
@vincerubinetti Thanks for that nice explanation! So I will not think about the cache aspect of this. As for the scaling with input gene set size. I think that would really only affect the data returned from the "check genes" section. In that section the user just gets info on their input gene size, so that table would linearly grow with more input genes, but that part is pretty small. However, for the main results that are returned after the model is trained contain all the genes in the network, all the terms in a gene set collection, so I would think that wouldn't really scale much with the input gene set size. However, if we want to show both human and a model species results at the same time (i.e. get results from two trained models), I would guess that would make the 5MB result size turn into 10MB.

**Review by ChristopherMancuso — APPROVED** [review]
I checked out the web server and it all seems to be working good and the changes you made seem to be working as they should.

**Pull request merged**
