### PR TITLE
Feedback for fixes from external feedback

### PR DESCRIPTION
**Pull request by ChristopherMancuso**
- changed figure on landing page to be gene symbols not names
- updated some text on the landing page
- updated a few tooltips
- added a button for FAQs page

### CODE REVIEW

**Comment by ChristopherMancuso** [comment]
@vincerubinetti The biggest change in here is that now PyGenePlexus has a parameter that can be set where it fails if there is not enough positives in the model. The limit is set to 5 by default. Is there a way you can have it display this information so a user knows they need at least 5 positives (not 5 input genes, but five genes able to be used as positives in training). This basically is needed because a user put in just one gene and had a bunch of questions about the results. The model is not meant to handle that.

**Comment by ChristopherMancuso** [comment]
@vincerubinetti A reviewer had questions about which exact species were used and they couldn't tell from the higher level names. I was wondering if you could add the info somewhere. I like the species selector box to say just the high level name when selected, but maybe when they click that field and they see the list of option we could add it there; either with the full name or just the tax id if there isn't space for the names. So something like

Human (Homo sapiens) icon
Mouse (Mus musculus) icon
Fly (Drosophila melanogaster) icon
Zebrafish (Danio rerio) icon
Worm (Caenorhabditis elegans) icon
Yeast (Saccharomyces cerevisiae) icon

or 

Human (TaxID 9606) icon
Mouse (TaxID 10090) icon
Fly (TaxID 7227) icon
Zebrafish (TaxID 7955) icon
Worm (TaxID 6239) icon
Yeast (TaxID 4932) icon

**Comment by ChristopherMancuso** [comment]
@vincerubinetti  maybe change in the last commit "identify different analyses" to "identify previous analyses"

**Comment by vincerubinetti** [comment]
Can you share the reviewer feedback with me regarding the web app? Sometimes (many times) reviewers ask for things that go against best practices, accessibility requirements, or just aren't the right solution to their problem. 

E.g. I tweaked the "Name" field tooltip because I don't think the change there adequately conveyed to the user what the purpose of the field is, just where it showed up.

I put the species scientific name in the dropdowns.

> @vincerubinetti The biggest change in here is that now PyGenePlexus has a parameter that can be set where it fails if there is not enough positives in the model. The limit is set to 5 by default. Is there a way you can have it display this information so a user knows they need at least 5 positives (not 5 input genes, but five genes able to be used as positives in training). This basically is needed because a user put in just one gene and had a bunch of questions about the results. The model is not meant to handle that.

If I'm understanding correctly, I can't just check how many genes they've entered in the box because they might be invalid/not in-network? 

First, we'd use the [`<Alert>` component](https://gene-plexus.netlify.app/testbed#alert) for this.

I think I'd show it under the main gene input text box if there are fewer than 5 entered. And if they run the "pre-check genes" step and fewer than 5 are valid, then we show it there too. And we prevent them from submitting the analysis with those warnings?

To cover the case where the user has > 5 genes entered and doesn't pre-check them, we could also show an alert when, say, < 10 genes were entered that says something like "warning: you haven't input many genes. if less than 5 of them are valid, the analysis will fail." 

We could just have a static alert that's always there, right next to the submit button, but that feels heavy handed. 

Let me know what you'd like to do.

**Comment by vincerubinetti** [comment]
> @vincerubinetti maybe change in the last commit "identify different analyses" to "identify previous analyses"

I think you're referring the fact that the name is used in the "recent analyses" section on the "load analysis" page, but the name is used elsewhere too. E.g. a user could open up a few tabs and run several analyses at once, and none of them are really "previous". But the name still helps them be distinguished from one another.

How about:

> (Optional) A name to quickly distinguish this analysis from others. Used as a filename when saving results, and shown anywhere an analysis summary or details is shown.

**Comment by ChristopherMancuso** [comment]
I like the latest Name tooltip text from the last comment!

**Comment by ChristopherMancuso** [comment]
I just forwarded you the email chain with the external reviewer feedback. 

For the too few positives message, you are understanding the way it works perfectly, and the main complication is if they don't pre-check their genes as you mentioned. If it isn't too hard to add the series of alerts like you were proposing then I think that is a great way to go. I also don't really like the idea of a static alert message, but if that ends up being the needed due to ease of implementation than that could work too.

**Review by vincerubinetti — APPROVED** [review]
Looks good to me now. Please take a look at the alert changes to the new analysis page I added in my most recent commit.

**Comment by ChristopherMancuso** [comment]
It is looking super close. The one thing I noticed is that if you have 5 genes in the input box, then check them, and there 4 left (Can reproduce with the first 5 genes in the human example) it gives the error message but the submit box is still abled to be clicked. Can you "grey" out the submit button in this case like you do when the input box has less than 5 genes?

**Pull request merged**
