### PR TITLE
update python package version

### PR DESCRIPTION
**Pull request by vincerubinetti**
- update python package to latest version f306e17
- make changes in cloud funcs and frontend as needed
- remove testbed button from homepage

### CODE REVIEW

**Comment by vincerubinetti** [comment]
@ChristopherMancuso Not sure if any of the comment verbage in `/frontend/src/api/types.ts` could be updated to match the change from `_tst` to `_res`.

**Comment by ChristopherMancuso** [comment]
@vincerubinetti I pulled this branched and tested the web server to see if it ran after running `run_local.sh` and it worked for me. I tried to run it on the netlfy preview and it didn't work. I can't remember what netlfy is doing and I think that is expected, but thought I would mention it

**Comment by ChristopherMancuso** [comment]
In `/frontend/src/api/types.ts` I think line 63 is the only on that would change from `sp_tst` to `sp_res`. For that document there are some places where if we want we can be more specific like in line 21 we have it just species as we know it needs to be the input species, but that could be referred to as `sp_trn`. Not sure when/if that matters to anyone.

The only real difference between the python package and web server is that in the python package as user can specific a `gsc_trn` which is used to find negative genes for training and also a `gsc_res` which is the gene sets that the training model is compared to. In the web server we force this to be the same in each case (defaults to Combined now). but that is why is is just `gsc` on line 73.

**Comment by vincerubinetti** [comment]
I'm at an appointment right now but the Netlify thing is expected since these are breaking changes and the Netlify version of the site is using the live Google Cloud functions, the old ones, but expecting them to be the new ones.

**Comment by vincerubinetti** [comment]
> In `/frontend/src/api/types.ts` I think line 63 is the only on that would change from `sp_tst` to `sp_res`. For that document there are some places where if we want we can be more specific like in line 21 we have it just species as we know it needs to be the input species, but that could be referred to as `sp_trn`. Not sure when/if that matters to anyone.
> 
> The only real difference between the python package and web server is that in the python package as user can specific a `gsc_trn` which is used to find negative genes for training and also a `gsc_res` which is the gene sets that the training model is compared to. In the web server we force this to be the same in each case (defaults to Combined now). But that is why it is just `gsc` on line 73.

Okay for consistency I updated `species` to be `sp_trn` in the cloud funcs and frontend.

Other than that, if it seems to be working, it seems like this is good to go.

**Review by ChristopherMancuso — APPROVED** [review]

**Pull request merged**
